package jammazwan.replaceme;

global java.util.Set controlSet;

rule "does it have a pom?"
no-loop
when
	ProjectFiles( hasPom, $val : "pom" )
then
	controlSet.add($val);
end


rule "does it have a README.md?"
no-loop
when
	ProjectFiles( hasReadme, $val : "README" )
then
	controlSet.add($val);
end

rule "does it have a NOTES.md?"
no-loop
when
	ProjectFiles( hasNotes, $val : "NOTES" )
then
	controlSet.add($val);
end


rule "does it have an EXTRA.md?"
no-loop
when
	ProjectFiles( hasExtra, $val : "EXTRA" )
then
	controlSet.add($val);
end


rule "does it have a Jenkinsfile?"
no-loop
when
	ProjectFiles( hasJenkins, $val : "Jenkins" )
then
	controlSet.add($val);
end


rule "is it adequately documented?"
no-loop
when
	ProjectFiles( hasReadme && hasNotes, $val : "adequatelyDocumented" )
then
	controlSet.add($val);
end

